# Generated by Django 4.1.7 on 2023-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'ordering': ['name'], 'verbose_name_plural': 'my_apps'},
        ),
    ]
