# Generated by Django 4.1.7 on 2023-03-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='recurrency_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAY'), (3, 'WEEK'), (4, 'MONTH'), (5, 'QUARTER'), (6, 'SEMESTER'), (7, 'YEAR')], default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='recurrency_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='recurrency_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAY'), (3, 'WEEK'), (4, 'MONTH'), (5, 'QUARTER'), (6, 'SEMESTER'), (7, 'YEAR')], default=1),
        ),
        migrations.AddField(
            model_name='outcome',
            name='recurrency_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'GIFT'), (4, 'DIVIDEND'), (5, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcome_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RENT'), (2, 'BILLS'), (3, 'CAR'), (4, 'TRAVEL'), (5, 'HEALTH'), (6, 'GROCERIES'), (7, 'FUN'), (8, 'CLOTHES'), (9, 'CHARITY'), (10, 'INVESTMENT'), (11, 'EDUCATION')]),
        ),
    ]
