# Generated by Django 4.1.7 on 2023-03-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0004_alter_balance_value_alter_income_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment_char',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='comment_char',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
