# Generated by Django 4.1.7 on 2023-03-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0005_income_comment_char_income_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='outcome',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='income',
            name='comment_char',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='comment_char',
        ),
    ]
